var classes = [{
  "prerequisites": "Freshman or sophomore standing; consent of instructor required for juniors and seniors",
  "description": "An introduction to the nature of culture, the organization of social relations, and the relationships between values and behavior. Attention to the human use of culture in adapting to environments and to language, technology, kinship, and religion as cultural systems. Case studies of Western and non-Western peoples.",
  "attributes": ["Social Science Div GER (01cr)",
               "Diversity-Global GER (01cr)",
              "Diversity-Dimens GER (01cr)",
              "BM Social Science (01cr)",
              "Introductory Course"],
  "term": "Spring Term 2014",
  "instructors": "Carla Daughtry",
  "course": "ANTH 110",
  "mode": "Standard",
  "title": "CULTURAL ANTHROPOLOGY",
  "final": "Wednesday, June 11, 2014 08:00 a.m. - 10:30 a.m.",
  "crn": "1142",
  "status": "Active",
  "time": "8:30-9:40pm MWF BRIG 224",
  "start": "Jan 06, 2014",
  "end": "Mar 19, 2014",
  "campus": "Appleton Main Campus",
  "units": 6,
  "enrollment": {"maximum": 40, "registered": 38, "waitlist": 0, "seats": 2}
}, {
  "prerequisites": "Freshman or sophomore standing; consent of instructor required for juniors and seniors",
  "description": "An introduction to the peoples and cultures of the world from 40,000 years ago to 2,000 years ago. Major events in world prehistory, such as the origins of agriculture, the rise of cities, and the spread of states, are examined and discussed. General trends in cultural evolution are proposed and evaluated. This course may not be taken on a Satisfactory/Unsatisfactory basis. ",
  "attributes": ["Social Science Div GER (01cr)", "Diversity-Global GER (01cr)", "BM Social Science (01cr)", "Introductory Course" ],
  "term": "Spring Term 2014",
  "instructors": "Peter Neal Peregrine",
  "course": "ANTH 120",
  "mode": "Standard",
  "title": "WORLD PREHISTORY",
  "final": "Tuesday, Jun 10, 2014 11:30 a.m. - 02:00 p.m.",
  "crn": "3160",
  "status": "Active",
  "time": "1:50-3:00 MWF BRIG 326",
  "start": "Mar 31, 2014",
  "end": "Jun 11, 2014",
  "campus": "Appleton Main Campus",
  "units": 6,
  "enrollment": {"maximum": 40, "registered": 25, "waitlist": 0, "seats": 15}
}, {
  "prerequisites": "ANTH 110, 120, or 140, preferably all three. Recommended for anthropology majors in the sophomore year; must be completed by the end of the junior year.",
  "description": "A study of the development of anthropology as a scholarly discipline and a method of inquiry. Consideration of theoretical perspectives such as evolutionism, historical particularism, functionalism, cultural materialism, structuralism, interpretive and postmodernist approaches, and also the significance of participant-observation and other field research strategies in shaping anthropological knowledge.",
  "attributes": ["Social Science Div GER (01cr)", "BM Social Science (01cr)", "Foundation/Gateway Course"],
  "term": "Spring Term 2014",
  "instructors": "Mary K. Good",
  "course": "ANTH 200",
  "mode": "Standard",
  "title": "HIST OF ANTHROPOLOGICAL IDEAS",
  "final": "Tuesday, Jun 10, 2014 03:00 p.m. - 05:30 p.m.",
  "crn": "3961",
  "status": "Active",
  "time": "03:10-04:20 MWF BRIG 305",
  "start": "Mar 31, 2014",
  "end": "Jun 11, 2014",
  "campus": "Appleton Main Campus",
  "units": 6,
  "enrollment": {"maximum": 20, "registered": 14, "waitlist": 0, "seats": 6}
},{
  "prerequisites": "ANTH 110, 120, or 140, preferably all three; non-anthropology majors must obtain consent of the instructor. Recommended for anthropology majors in the sophomore year; must be completed by the end of the junior year.",
  "description": "An introduction to basic assumptions and methods of research in sociocultural anthropology, including participant observation, ethnographic interview, focus groups, cognitive methods, survey, and census. Students gain hands-on experience in research.",
  "attributes": ["Social Science Div GER (01cr)", "BM Social Science (01cr)", "Foundation/Gateway Course" ],
  "term": "Spring Term 2014",
  "instructors": "Mary K. Good",
  "course": "ANTH 210",
  "mode": "Standard",
  "title": "RES METHODS IN CULTURAL ANTH",
  "final": "Monday, Jun 09, 2014 11:30 a.m. - 02:00 p.m.",
  "crn": "3158",
  "status": "Active",
  "time": "11:10-12:20 MWF BRIG 305",
  "start": "Mar 31, 2014",
  "end": "Jun 11, 2014",
  "campus": "Appleton Main Campus",
  "units": 6,
  "enrollment": {"maximum": 12, "registered": 9, "waitlist": 1, "seats": 2}
},{
  "prerequisites": "ANTH 140 or consent of instructor, AND sophomore standing",
  "description": "Students will develop an understanding of modern human biology as the outcome of interactions between evolved genomes and the myriad environments in which we are born, develop and live out our lives. Topics of study will include evolutionary approaches to reproduction, growth and development, health, behavior, adaptation, and life history.",
  "attributes": ["Social Science Div GER (01cr)", "BM Social Science (01cr)", "Foundation/Gateway Course"],
  "term": "Spring Term 2014",
  "instructors": "Mark Jenike",
  "course": "ANTH 340",
  "mode": "Standard",
  "title": "HUMAN BIOL, EVOLUTN, & HEALTH",
  "final": "Monday, Jun 09, 2014 08:00 a.m. - 10:30 a.m.",
  "crn": "3163",
  "status": "Active",
  "time": "09:50-11:00 MWF BRIG 224",
  "start": "Mar 31, 2014",
  "end": "Jun 11, 2014",
  "campus": "Appleton Main Campus",
  "units": 6,
  "enrollment": {"maximum": 25, "registered": 14, "waitlist": 0, "seats": 11}
},{
  "prerequisites": "None",
  "description": "An introductory survey of the art and architecture of Europe and North America from the Renaissance to the Modern era. Particular emphasis on viewing works of art and architecture within their historical and cultural context.",
  "attributes": ["Fine Arts Div GER (01cr)", "Introductory Course"],
  "term": "Spring Term 2014",
  "instructors": "Benjamin C. Tilghman",
  "course": "ARHI 102",
  "mode": "Standard",
  "title": "SURVEY II:RENAISS TO MODERN",
  "final": "Monday, Jun 09, 2014 11:30 a.m. - 02:00 p.m.",
  "crn": "3219",
  "status": "Active",
  "time": "11:10-12:20 MWF WRIS 224",
  "start": "Mar 31, 2014",
  "end": "Jun 11, 2014",
  "campus": "Appleton Main Campus",
  "units": 6,
  "enrollment": {"maximum": 60, "registered": 35, "waitlist": 0, "seats": 25}
},{
  "prerequisites": "ARHI 100 or sophomore standing",
  "description": "A study of Greek art and architecture to the end of the fourth century B.C. Topics include the great sanctuaries at Olympia, Delphi, and Athens; the development of mythological narrative in sculpture and vase painting; the political and propagandistic function of Greek art; and the beginning of portraiture.",
  "attributes": ["Fine Arts Div GER (01cr)", "Foundation/Gateway Course"],
  "term": "Spring Term 2014",
  "instructors": "Carol L. Lawton",
  "course": "ARHI 200",
  "mode": "Standard",
  "title": "ARCHAIC & CLASSICAL GREEK ART",
  "final": "Tuesday, Jun 10, 2014 11:30 a.m. - 02:00 p.m.",
  "crn": "3220",
  "status": "Active",
  "time": "08:30-09:40 MWF WRIS 221",
  "start": "Mar 31, 2014",
  "end": "Jun 11, 2014",
  "campus": "Appleton Main Campus",
  "units": 6,
  "enrollment": {"maximum": 35, "registered": 10, "waitlist": 0, "seats": 25}
},{
  "prerequisites": "ARHI 100 or sophomore standing",
  "description": "The arts of this period are famous for their beauty and grandeur, from soaring cathedrals to delicate paintings. We will consider these beautiful works alongside historical changes within the cultural, economic, and ideological fabric of society, as well as contemporary theories about social contruction and the nature of objects.",
  "attributes": ["Fine Arts Div GER (01cr)", "Foundation/Gateway Course"],
  "term": "Spring Term 2014",
  "instructors": "Benjamin C. Tilghman",
  "course": "ARHI 213",
  "mode": "Standard",
  "title": "GOTHIC & N RENAISSANCE ART",
  "final": "Tuesday, Jun 10, 2014 03:00 p.m. - 05:30 p.m.",
  "crn": "3221",
  "status": "Active",
  "time": "03:10-04:20 MWF WRIS 221",
  "start": "Mar 31, 2014",
  "end": "Jun 11, 2014",
  "campus": "Appleton Main Campus",
  "units": 6,
  "enrollment": {"maximum": "Unlimited", "registered": 17}
},{
  "prerequisites": "None",
  "description": "An introduction to studio art and the fundamental principles of design. Projects, lectures, readings, class discussions, and critiques examine elements of two-dimensional, three-dimensional and time-based design. Historic and contemporary approaches are considered as well as the evolution of technology and the continuum of visual expression. Emphasis is placed on developing the practical and critical thinking skills required in art-making.",
  "attributes": ["Fine Arts Div GER (01cr)", "Introductory Course"],
  "term": "Spring Term 2014",
  "instructors": "Sarah Gross",
  "course": "ART 100",
  "mode": "Standard",
  "title": "INTRODUCTION TO STUDIO ART",
  "final": "Monday, Jun 09, 2014 03:00 p.m. - 05:30 p.m.",
  "crn": "3237",
  "status": "Active",
  "time": "01:00-04:30 MW WRIS 102",
  "start": "Mar 31, 2014",
  "end": "Jun 11, 2014",
  "campus": "Appleton Main Campus",
  "units": 6,
  "enrollment": {"maximum": 20, "registered": 15, "waitlist": 12, "seats": 0}
},{
  "prerequisites": "None",
  "description": "An introduction to drawing, emphasizing the development of the observational and critical thinking skills important to art-making. Class work is based on exercises that strengthen visual research capabilities, drawing abilities, and mark-making techniques with a variety of tools. Assigned projects address fundamental technical and conceptual problems suggested by historical and contemporary artistic practice. Lectures, readings, discussions, and critiques explore elements of concept and design pertinent to drawing as a medium.",
  "attributes": ["Fine Arts Div GER (01cr)", "Introductory Course"],
  "term": "Spring Term 2014",
  "instructors": "Tony Gerald Conrad",
  "course": "ART 110",
  "mode": "Standard",
  "title": "INTRODUCTION TO DRAWING",
  "final": "Tuesday, Jun 10, 2014 11:30 a.m. - 02:00 p.m.",
  "crn": "3238",
  "status": "Active",
  "time": "08:30-12:00 MW MEMO 104",
  "start": "Mar 31, 2014",
  "end": "Jun 11, 2014",
  "campus": "Appleton Main Campus",
  "units": 6,
  "enrollment": {"maximum": 15, "registered": 12, "waitlist": 9, "seats": 0}
},{
  "prerequisites": "ART 100 or ART 110, or consent of instructor",
  "description": "This course is a combination of research and studio practice. Through lectures, readings and discussions the class will survey the history of ceramics with the goal of informing the studio work for the course. Students will engage in independent research to develop ideas and critical thinking as well as building on a variety of ceramic skills to create a personal body of work.",
  "attributes": ["Fine Arts Div GER (01cr)", "Foundation/Gateway Course"],
  "term": "Spring Term 2014",
  "instructors": "Sarah Gross",
  "course": "ART 256",
  "mode": "Standard",
  "title": "TOP: HERE TODAY, HERE TOMORROW",
  "final": "Tuesday, Jun 10, 2014 11:30 a.m. - 02:00 p.m.",
  "crn": "3239",
  "status": "Active",
  "time": "08:30-12:00 MW WRIS 124",
  "start": "Mar 31, 2014",
  "end": "Jun 11, 2014",
  "campus": "Appleton Main Campus",
  "units": 6,
  "enrollment": {"maximum": 10, "registered": 9, "waitlist": 2, "seats": 0}
},{
  "prerequisites": "None",
  "description": "An introductory course focusing on human reproduction to demonstrate some basic biological principles. The course includes discussion of cellular and organismal processes related to the development of human biological complexity. Current research in reproductive biology and its impact on the individual and society is considered. Lecture and laboratory. Primarily for non-science majors; credit not applicable to the biology major.",
  "attributes": ["NS Lab Course GER (01cr)", "Nat Science Div GER (01cr)", "BM Natural Science (01cr)", "Introductory Course"],
  "term": "Spring Term 2014",
  "instructors": "Nancy A. Wall",
  "course": "BIOL 100",
  "mode": "Standard",
  "title": "BIOLOGY OF HUMAN REPRODUCTION",
  "final": "Monday, Jun 09, 2014 11:30 a.m. - 02:00 p.m.",
  "crn": "3021",
  "status": "Active",
  "time": "11:10-12:20 MWF SCIE 202 01:00-04:00 T SCIE 302",
  "start": "Mar 31, 2014",
  "end": "Jun 11, 2014",
  "campus": "Appleton Main Campus",
  "units": 6,
  "enrollment": {"maximum": 24, "registered": 24, "waitlist": 0, "seats": 0}
},{
  "prerequisites": "BIOL 110, BIOL 130, or departmental examination",
  "description": "Development, morphology, physiology, and ecology of plants, animals, fungi and unicellular organisms will be compared in evolutionary context. Phylogenic relationships, ecological interactions, and ecosystem processes will be explored. Lecture and laboratory.",
  "attributes": ["NS Lab Course GER (01cr)", "Nat Science Div GER (01cr)", "BM Natural Science (01cr)", "Introductory Course"],
  "term": "Spring Term 2014",
  "instructors": "Judith Humphries",
  "course": "BIOL 150",
  "mode": "Standard",
  "title": "BIOLOGY: ORGANISMS-ECOSYSTEMS",
  "final": "Tuesday, Jun 10, 2014 11:30 a.m. - 02:00 p.m.",
  "crn": "3016",
  "status": "Active",
  "time": "08:30-09:40 MWF SCIE 102 01:00-04:00 T YOUN 333",
  "start": "Mar 31, 2014",
  "end": "Jun 11, 2014",
  "campus": "Appleton Main Campus",
  "units": 6,
  "enrollment": {"maximum": 30, "registered": 25, "waitlist": 0, "seats": 5}
},{
  "prerequisites": "BIOL 150 or consent of instructor",
  "description": "None",
  "attributes": ["Nat Science Div GER (01cr)", "Quantitative Analy GER (01cr)", "BM Natural Science (01cr)", "Introductory Course"],
  "term": "Spring Term 2014",
  "instructors": "Kimberly Dickson",
  "course": "BIOL 170",
  "mode": "Standard",
  "title": "BIOLOGY: EXPERIMENTAL ANALYSIS (Q)",
  "final": "Monday, Jun 09, 2014 08:00 a.m. - 10:30 a.m.",
  "crn": "3012",
  "status": "Active",
  "time": "09:50-11:00 MWF SCIE 102 09:00-10:50 T BRIG 421",
  "start": "Mar 31, 2014",
  "end": "Jun 11, 2014",
  "campus": "Appleton Main Campus",
  "units": 6,
  "enrollment": {"maximum": 24, "registered": 23, "waitlist": 0, "seats": 1}
},{
  "prerequisites": "CHEM 115 or placement examination",
  "description": "Introduction to the study of chemistry, for students who have taken high school chemistry or CHEM 115, emphasizing stuctural and quantitative models of chemical behavior. Topics include bonding, thermochemistry, equilibrium, kinetics, and related applications. Three lectures and one laboratory per week. Enrollment is determined by placement examination for students who have not completed CHEM 115. See the chemistry department's web page for placement examination information.",
  "attributes": ["NS Lab Course GER (01cr)", "Nat Science Div GER (01cr)", "Quantitative Analy GER (01cr)", "BM Natural Science (01cr)", "Introductory Course"],
  "term": "Spring Term 2014",
  "instructors": "Jay R. Stork",
  "course": "CHEM 116",
  "mode": "Standard",
  "title": "PRIN OF CHEM:ENERG & DYNAMICS (Q)",
  "final": "Tuesday, Jun 10, 2014 08:00 a.m. - 10:30 a.m.",
  "crn": "3113",
  "status": "Active",
  "time": "01:50-03:00 MWF SCIE 102 08:00-11:00 T SCIE 116",
  "start": "Mar 31, 2014",
  "end": "Jun 11, 2014",
  "campus": "Appleton Main Campus",
  "units": 6,
  "enrollment": {"maximum": 22, "registered": 19, "waitlist": 0, "seats": 3}
},{
  "prerequisites": "CHEM 116",
  "description": "This course focuses on the fundamental chemical processes that control Earth's atmosphere, ocean, soil, and climate. The course emphasizes the mechanisms that regulate the flow of energy in different ecosystems, the environmental role of particulate matter and solar radiation, chemistry-climate relationships, and the anthropogenic impact on the environment.",
  "attributes": ["Nat Science Div GER (01cr)", "BM Natural Science (01cr)", "Foundation/Gateway Course"],
  "term": "Spring Term 2014",
  "instructors": "Deanna L. Donohoue",
  "course": "CHEM 212",
  "mode": "Standard",
  "title": "ATMOSPHER & ENVIRONMENTAL CHEM",
  "final": "Monday, Jun 09, 2014 03:00 p.m. - 05:30 p.m.",
  "crn": "4004",
  "status": "Active",
  "time": "12:30-01:40 MWF SCIE 230",
  "start": "Mar 31, 2014",
  "end": "Jun 11, 2014",
  "campus": "Appleton Main Campus",
  "units": 6,
  "enrollment": {"maximum": "Unlimited", "registered": 6}
},{
  "prerequisites": "CHEM 250",
  "description": "A study of organic reactions and their mechanisms. The focus of the class is synthesis, both in the concrete sense of building molecules and in the abstract sense of pulling together disparate concepts to solve problems. Case studies from the polymer and pharmaceutical industries underline the relevance of the discipline to everyday life. One four-hour laboratory per week.",
  "attributes": ["NS Lab Course GER (01cr)", "Nat Science Div GER (01cr)", "BM Natural Science (01cr)", "Foundation/Gateway Course"],
  "term": "Spring Term 2014",
  "instructors": "Stefan Debbert",
  "course": "CHEM 252",
  "mode": "Standard",
  "title": "ORGANIC CHEMISTRY II",
  "final": "Tuesday, Jun 10, 2014 08:00 a.m. - 10:30 a.m.",
  "crn": "3117",
  "status": "Active",
  "time": "01:50-03:00 MWF SCIE 202 08:00-12:00 T SCIE 222",
  "start": "Mar 31, 2014",
  "end": "Jun 11, 2014",
  "campus": "Appleton Main Campus",
  "units": 6,
  "enrollment": {"maximum": 20, "registered": 18, "waitlist": 3, "seats": 0}
},{
  "prerequisites": "CHEM 210 or consent of instructor",
  "description": "An advanced course in instrumental methods of quantification and identification in modern chemistry. Emphasis on instrument design, operating principles, interpretation of instrumental data, and discrimination between techniques. Discussion of spectroscopic, chromatographic, and electrochemical techniques and their application in fundamental and applied research. Three lectures and one laboratory per week.",
  "attributes": ["NS Lab Course GER (01cr)", "Nat Science Div GER (01cr)", "BM Natural Science (01cr)", "Advanced Course"],
  "term": "Spring Term 2014",
  "instructors": "Deanna L. Donohoue",
  "course": "CHEM 410",
  "mode": "Standard",
  "title": "INSTRUMENTAL ANALYSIS",
  "final": "Wednesday, Jun 11, 2014 08:00 a.m. - 10:30 a.m.",
  "crn": "3115",
  "status": "Active",
  "time": "09:00-10:50 TR SCIE 230 01:00-04:00 T SCIE 122",
  "start": "Mar 31, 2014",
  "end": "Jun 11, 2014",
  "campus": "Appleton Main Campus",
  "units": 6,
  "enrollment": {"maximum": "Unlimited", "registered": 7}
}];


var subjects = ["Anthropology (ANTH)",
    "Art (ART)",
    "Art History (ARHI)",
    "Biology (BIOL)",
    "Biomedical Ethics (BIET)",
    "Chemistry( CHEM)",
    "Chinese and Japanese (CHJA)",
    "Classics (CLAS)",
    "Computer Science (CMSC)",
    "Dimensions of Diversity Classes (D)",
    "East Asian Studies Program (EAST)",
    "Economics (ECON)",
    "Education (EDUC)",
    "Education Studies (EDST)",
    "English(ENG)",
    "Environmental Studies (ENST)",
    "Ethnic Studies (ETST)",
    "Film Studies (FIST)",
    "Foreign Language Competency Classes (A,M)",
    "French (FREN)",
    "Freshman Studies (FRST)",
    "Gender Studies (GEST)",
    "Geology (GEOL)",
    "German (GER)",
    "Global Diversity Classes (G)",
    "Government (GOVT)",
    "History (HIST)",
    "Linguistics (LING)",
    "Mathematics (MATH)",
    "Music Composition and Arranging (MUCA)",
    "Music Education and Pedagogy (MUEP)",
    "Music Ensemble Performance Studies (MUEN)",
    "Music History (MUHI)",
    "Applied Music Individual Instruction (MUIN)",
    "Music Repertoire - Performance Study (MURP)",
    "Music Theory (MUTH)",
    "Philosophy (PHIL)",
    "Physics (PHYS)",
    "Psychology (PSYC)",
    "Quantitative Classes (Q)",
    "Religious Studies (RLST)",
    "Russian (RUSS)",
    "Spanish (SPAN)",
    "Speaking-Intensive Classes (S)",
    "Theatre Arts (THAR)",
    "University Courses (UNIC)",
    "Writing-Intensive Classes (W)"];
